# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: seL4 docs

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: "This site is for displaying seL4 related documentation.  Pull requests are welcome."
github_username:
  - "sel4"
  - "sel4proj"

collections:
  -sel4_release
  -camkes_release

collections:
  sel4_release:
    output: true
  camkes_release:
    output: true

sel4_master: "8.0.0"
sel4_mcs: "5.2.0-mcs"
camkes: "3.2.0"


# Front matter defaults:
defaults:
  - scope:
      path: ""
      type: sel4_release
    values:
      layout: "release"
  - scope:
      path: ""
      type: camkes_release
    values:
      layout: "release"
  -
    scope:
      path: ""
    values:
      layout: "default"


# Build/plugin settings.  These settings configure plugins.
# Themes and plugins transparently add files to the site project.  To see what plugins
# are being used run `bundle show`.  To see what files are contributed by each plugin:
#  ls `bundle show $plugin_name`
# The jekyll-theme-bootstrap dependency probably contributes the most files to site generation, so it would
# be the first place to look if something weird is happening with layout/theming.
# This theme provides a sass port of bootstrap that is imported using our assets/css/style.scss file.
theme: jekyll-theme-bootstrap
markdown: Kramdown

plugins:
  # Sets the page title to the first heading.  Removes need for title to be set in every file
  - jekyll-titles-from-headings
  # Converts markdown relative links to valid html urls.
  - jekyll-relative-links
  # Default includes .md files to be templated without needing the --- front matter.
  - jekyll-optional-front-matter
  # Adds a sitemap.xml to site for webcrawlers
  - jekyll-sitemap
  # Adds a table of contents to top of page if toc: true is set in the front matter.
  - jekyll-toc

kramdown:
  input: GFM

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

optional_front_matter:
# Set this to false if you want .md files to be accessible also
  remove_originals: true

# Exclude files from processing. dotfiles don't seem to be included by default
exclude:
  - Gemfile
  - Gemfile.lock
  - dependencies
  - Makefile
  - README.md
  - tools/
  - assets/css/highlighting/demos
  - assets/css/highlighting/tools
  - assets/css/highlighting/index.html
